import org.h2.server.web.WebServlet;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.servlet.ServletRegistrationBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

@SpringBootApplication
@ComponentScan(basePackages={"org.scottrbrtsn.learning.server"})
@EnableJpaRepositories
public class Application {

	public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
//		SpringApplicationBuilder builder = new SpringApplicationBuilder(App.class);
//		builder.headless(false).run(args);
	}

	/**
	 * Loads a (autogenerated) developer web interface mapped to DOMAIN/console.
	 * @return
	 * @requires the service to remain running to persist data
     * Update db.migrations to ensure students are added to the DB
	 */
	@Bean
	public ServletRegistrationBean h2servletRegistration() {
		ServletRegistrationBean registration = new ServletRegistrationBean(new WebServlet());
		registration.addUrlMappings("/console/*");
		return registration;
	}
}